# Generated by Django 3.0.6 on 2020-06-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('logo', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=500)),
                ('position', models.FloatField(default=0)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
